[tool.poetry]
name = "bma"
version = "0.1.0"
description = "Code for running the bma game website"
authors = ["--- <---->"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^3.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
